Trie depth on retrieve value
ElrondNetwork/wasm-vm-v1_2 pull request #4
Opened 2022-10-19 14:37 UTC by BeniaminDrasovean

2022-10-19 15:33 UTC, AdoAdoAdo requested changes

2022-10-19 15:33 UTC, AdoAdoAdo commented on go.mod
> +	github.com/ElrondNetwork/elrond-vm-common v1.3.23-0.20221019113258-ca9342453fa4
needs a proper tag before merging.

2022-10-21 14:34 UTC, AdoAdoAdo approved these changes

2022-10-21 14:53 UTC, ssd04 approved these changes

2022-10-21 15:01 UTC, camilbancioiu approved these changes

2022-10-27 08:02 UTC, merged